#pragma config(Motor,  port1,           frontLeft,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           bottomLeft,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           bottomRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightGrabber,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftGrabber,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           topLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           topRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          backRight,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){

		//chassis
		motor[frontLeft] = vexRT[Ch3];
		//motor[backLeft] = vexRT[Ch3];
		motor[frontRight] = vexRT[Ch2];
		//motor[backRight] = vexRT[Ch2];
		//lift motors
		motor[bottomLeft] = vexRT[Ch2Xmtr2];
		motor[bottomRight] = vexRT[Ch2Xmtr2];
		motor[topLeft] = vexRT[Ch2Xmtr2];
		motor[topRight] = vexRT[Ch2Xmtr2];
		//grabber motors
		if (vexRT[Btn5UXmtr2] &&! vexRT[Btn5DXmtr2]) {
			motor[leftGrabber] = 127;
		};
		if (vexRT[Btn5DXmtr2] &&! vexRT[Btn5UXmtr2]) {
			motor[leftGrabber] = -127;
		};
		if (!(vexRT[Btn5UXmtr2] || vexRT[Btn5DXmtr2])) {
			motor[leftGrabber] = 0;
		};
		if (vexRT[Btn6UXmtr2] &&! vexRT[Btn6DXmtr2]) {
			motor[rightGrabber] = 127;
		};
		if (vexRT[Btn6DXmtr2] &&! vexRT[Btn6UXmtr2]) {
			motor[rightGrabber] = -127;
		};
		if (!(vexRT[Btn6UXmtr2] || vexRT[Btn6DXmtr2])) {
			motor[rightGrabber] = 0;
		};


	};
}
